version: 2

defaults: &defaults
aliases:
  - &restore_cache
      keys:
        - v2-dependencies-{{ checksum "package.json" }}
        - v2-dependencies-
  - &save_cache
      paths:
        - node_modules
      key: v2-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: npm install
      - run: npm start
      - save_cache: *save_cache
